import cv2

#-----Reading the image-----------------------------------------------------
img = cv2.imread('capture_hb/cam4.jpg',1)
cv2.namedWindow('img',cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 1080,811)
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyWindow("img")
#-----Converting image to LAB Color model-----------------------------------
lab= cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
cv2.namedWindow('lab',cv2.WINDOW_NORMAL)
cv2.resizeWindow('lab', 1080,811)
cv2.imshow("lab",lab)
cv2.waitKey(0)
cv2.destroyWindow("lab")
#-----Splitting the LAB image to different channels-------------------------
l, a, b = cv2.split(lab)
cv2.namedWindow('l_channel',cv2.WINDOW_NORMAL)
cv2.resizeWindow('l_channel', 1080,811)
cv2.imshow('l_channel', l)
cv2.waitKey(0)
cv2.destroyWindow("l_channel")
cv2.namedWindow('a_channel',cv2.WINDOW_NORMAL)
cv2.resizeWindow('a_channel', 1080,811)
cv2.imshow('a_channel', a)
cv2.waitKey(0)
cv2.destroyWindow("a_channel")
cv2.namedWindow('b_channel',cv2.WINDOW_NORMAL)
cv2.resizeWindow('b_channel', 1080,811)
cv2.imshow('b_channel', b)
cv2.waitKey(0)
cv2.destroyWindow("b_channel")
#-----Applying CLAHE to L-channel-------------------------------------------
clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
cl = clahe.apply(l)
cv2.namedWindow('CLAHE output',cv2.WINDOW_NORMAL)
cv2.resizeWindow('CLAHE output', 1080,811)
cv2.imshow('CLAHE output', cl)
cv2.waitKey(0)
cv2.destroyWindow("CLAHE output")
#-----Merge the CLAHE enhanced L-channel with the a and b channel-----------
limg = cv2.merge((cl,a,b))
cv2.namedWindow('limg',cv2.WINDOW_NORMAL)
cv2.resizeWindow('limg', 1080,811)
cv2.imshow('limg', limg)
cv2.waitKey(0)
cv2.destroyWindow("limg")
#-----Converting image from LAB Color model to RGB model--------------------
final = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
cv2.namedWindow('final',cv2.WINDOW_NORMAL)
cv2.resizeWindow('final', 1080,811)
cv2.imshow('final', final)
cv2.imwrite("contrastoutput.jpg", final)
cv2.waitKey(0)
cv2.destroyWindow("final")

#_____END_____#